import { ToolSchema } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

const ToolInputSchema = ToolSchema.shape.inputSchema;
type ToolInput = z.infer<typeof ToolInputSchema>;

export const ToolOutputSchema = ToolSchema.shape.outputSchema;
type ToolOutput = z.infer<typeof ToolOutputSchema>;

// Schemas
export const PingSchema = z.object({});

export const GetRelevantQuestionsSchema = z.object({
	query: z
		.string()
		.describe(
			"The query to get relevant data questions for, this could be a high level task or question the user is asking or hoping to get answered. Do minimal processing of the original question. You can even pass the complete raw query as it is, the system is smart to make sense of it as it has access to the entire schema. Do not add analytical hints or directions.",
		),
	additionalContext: z
		.string()
		.describe(
			"Additional context to add to the query, this might be older data returned for previous questions or any other relevant context that might help the system generate better questions.",
		)
		.optional(),
	datasourceIds: z
		.array(z.string())
		.describe(
			"The datasources to get questions for, this is the ids of the datasources to get data from. Each id is a GUID string.",
		),
});

export const GetRelevantQuestionsOutputSchema = z.object({
	questions: z.array(
		z.object({
			question: z.string(),
			datasourceId: z.string(),
		}),
	),
});

export const GetAnswerSchema = z.object({
	question: z
		.string()
		.describe(
			"The question to get the answer for, these are generally the questions generated by the getRelevantQuestions tool.",
		),
	datasourceId: z
		.string()
		.describe(
			"The datasource to get the answer for, this is the id of the datasource to get data from",
		),
});

export const GetAnswerOutputSchema = z.object({
	data: z.string().describe("The csv data as an answer to the question"),
	session_identifier: z
		.string()
		.describe(
			"The session identifier for the answer, use for liveboard creation",
		),
	generation_number: z
		.number()
		.describe(
			"The generation number for the answer, use for liveboard creation",
		),
	frame_url: z
		.string()
		.describe(
			"A url which can be used to view the answer in an iframe in the browser",
		),
	fields_info: z
		.string()
		.describe("Information about the fields in the answer"),
});

export const CreateConversationSchema = z.object({
	data_source_id: z
		.string()
		.optional()
		.describe(
			"The data source to query. Provide this when the user has specified or confirmed a data source, or when context makes a particular source obvious. Omit it to let ThoughtSpot automatically select the most relevant source based on the question.",
		),
});

export const CreateConversationOutputSchema = z.object({
	analytical_session_id: z
		.string()
		.describe(
			"Identifier for the session. Use this to send messages or get updates on the session.",
		),
});

export const SendConversationMessageSchema = z.object({
	analytical_session_id: z
		.string()
		.describe("Identifier of the session to send the message to."),
	message: z
		.string()
		.describe(
			"A natural language analytical question or follow-up to send to the ThoughtSpot agent.",
		),
});

export const SendConversationMessageOutputSchema = z.object({
	success: z.boolean().describe("Whether the message was successfully sent."),
});

export const GetConversationUpdatesSchema = z.object({
	analytical_session_id: z
		.string()
		.describe("Identifier of the session to get updates from."),
});

export const ConversationUpdateSchema = z.object({
	type: z
		.enum(["text", "text_chunk", "answer"])
		.describe(
			"The type of update: `text` or `text_chunk` for a natural language message from the agent, or `answer` for a data visualization with query results. Determines which other fields are populated.",
		),
	text: z
		.string()
		.optional()
		.describe(
			"The text content of the message. Only present when `type` is `text` or `text_chunk`. If `type` is `text_chunk`, combine the chunks of text together to form the complete message.",
		),
	answer_id: z
		.string()
		.optional()
		.describe(
			"A unique identifier for the answer. Only present when `type` is `answer`. Use this field to identify this answer when using the `create_dashboard` tool.",
		),
	answer_title: z
		.string()
		.optional()
		.describe(
			"A human-readable title describing what the answer shows. Only present when `type` is `answer`.",
		),
	answer_query: z
		.string()
		.optional()
		.describe(
			"The search query ThoughtSpot used to generate the answer. Only present when `type` is `answer`. Useful for explaining to the user what data was queried or diagnosing unexpected results.",
		),
	iframe_url: z
		.string()
		.optional()
		.describe(
			"An embeddable URL for displaying the answer as an interactive visualization. Only present when `type` is `answer`. Use this to render a live chart or table if your environment supports iframes.",
		),
});

export const GetConversationUpdatesOutputSchema = z.object({
	session_updates: z
		.array(ConversationUpdateSchema)
		.describe(
			"List of updates from the session. This may be an empty list if the agent is still thinking, instead use the `is_done` flag to know whether the agent response is complete.",
		),
	is_done: z
		.boolean()
		.describe(
			"Whether the ThoughtSpot agent has finished responding. If not `is_done` is false, make another `get_session_updates` call to get the next set of updates.",
		),
});

export const CreateLiveboardSchema = z.object({
	name: z.string().describe("The name of the liveboard to create"),
	answers: z
		.array(
			z.object({
				question: z.string(),
				session_identifier: z.string(),
				generation_number: z.number(),
			}),
		)
		.describe(
			"The answers to create the liveboard from, these are the answers generated by the getAnswer tool.",
		),
	noteTile: z.string().describe(`
        Create a summary of the answers to the queries asked by the user along with all the analysis done on the data.
        The output format is an html note tile which can have custom styles and formatting. Use emojis, styling and icons to make it more visually appealing.
        Follow these MANDATORY rules for styling:
        - Put the whole note tile in a single line and no line breaks. Also there should be no unnecessary white spaces.
        - The html output in the note tile can have white spaces. Use <br> or <tab> if needed to use white spaces in the note tile.
        - Use padding, margin and line height to create space between the elements in the note tile and make it more readable.

        Use this as an example(ignore the line breaks and white spaces):

        <h2 class=\"theme-module__editor-h2\" dir=\"ltr\" style=\"text-align: center;\">
	        <span style=\"white-space: pre-wrap;\">\"Heading of note\"</span>
        </h2>
        <p class=\"theme-module__editor-paragraph\" dir=\"ltr\">
            <span style=\"white-space: pre-wrap;\">
                Comprehensive summary of analysis done and answers to queries asked by user. Use colors and styles in the html to make it more readable and visually appealing.
                Also add the date and time of the analysis to the note tile in the header of the note tile. The format should be like this: Generated on <date> <time>
            </span>
        </p>
        <div class=\"pinboard-note-tile-module__noteTileBg editor-module__bgNode\"></div>
        `),
});

export const GetDataSourceSuggestionsSchema = z.object({
	query: z
		.string()
		.describe(`The query to get data source suggestions for, this could be a high level task or question the user is asking or hoping to get answered.
         There can be multiple data sources. Each data source can be used to get the data for the user's query using the other tools getRelevantQuestions and getAnswer.`),
});

export const AnswerSchema = z.object({
	answer_id: z
		.string()
		.describe(
			"The unique identifier for the answer. Provide the `answer_id` value returned from get_session_updates for an update where `type` is `answer`.",
		),
	title: z
		.string()
		.describe(
			"Title of the answer. Provide a brief description of the answer, or the question which the answer is answering.",
		),
});

export const CreateDashboardSchema = z.object({
	title: z.string().describe("Title of the dashboard to be created."),
	answers: z
		.array(AnswerSchema)
		.describe("List of answers to add to the dashboard."),
	note_tile: z.string().describe(`
        Create a summary of the answers to the queries asked by the user along with all the analysis done on the data.
        The output format is an HTML note tile which can have custom styles and formatting. Use emojis, styling and icons to make it more visually appealing.
        Follow these MANDATORY rules for styling:
        - Put the whole note tile in a single line and no line breaks. Also there should be no unnecessary white spaces.
        - The HTML output in the note tile can have white spaces. Use <br> or <tab> if needed to use white spaces in the note tile.
        - Use padding, margin and line height to create space between the elements in the note tile and make it more readable.

        Use this as an example(ignore the line breaks and white spaces):

        <h2 class=\"theme-module__editor-h2\" dir=\"ltr\" style=\"text-align: center;\">
	        <span style=\"white-space: pre-wrap;\">\"Heading of note\"</span>
        </h2>
        <p class=\"theme-module__editor-paragraph\" dir=\"ltr\">
            <span style=\"white-space: pre-wrap;\">
                Comprehensive summary of analysis done and answers to queries asked by user. Use colors and styles in the html to make it more readable and visually appealing.
                Also add the date and time of the analysis to the note tile in the header of the note tile. The format should be like this: Generated on <date> <time>
            </span>
        </p>
        <div class=\"pinboard-note-tile-module__noteTileBg editor-module__bgNode\"></div>
        `),
});

export const CreateDashboardOutputSchema = z.object({
	link: z
		.string()
		.describe(
			"A URL link to the created dashboard. Provide this link to the user to view the dashboard.",
		),
});

export enum ToolName {
	// V1
	Ping = "ping",
	GetRelevantQuestions = "getRelevantQuestions",
	GetAnswer = "getAnswer",
	CreateLiveboard = "createLiveboard",
	GetDataSourceSuggestions = "getDataSourceSuggestions",
	// V2 (Spotter 3)
	CheckConnectivity = "check_connectivity",
	CreateAnalysisSession = "create_analysis_session",
	SendSessionMessage = "send_session_message",
	GetSessionUpdates = "get_session_updates",
	CreateDashboard = "create_dashboard",
}

export const toolDefinitionsV1 = [
	{
		name: ToolName.Ping,
		description: "Simple ping tool to test connectivity and Auth",
		inputSchema: zodToJsonSchema(PingSchema) as ToolInput,
		annotations: {
			title: "Test Connection",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateLiveboard,
		description: "Create a liveboard from a list of answers",
		inputSchema: zodToJsonSchema(CreateLiveboardSchema) as ToolInput,
		annotations: {
			title: "Create Liveboard from Answers",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetDataSourceSuggestions,
		description:
			"Get data source suggestions for a query. Use this tool only if there is not datasource id provided in the context or the users query. If mulitple data sources are returned, and the confidence difference between the top two data sources is less than 0.3, ask the user to select the most relevant data source. Otherwise use the data source with the highest confidence to get the relevant questions and answers for the query.",
		inputSchema: zodToJsonSchema(GetDataSourceSuggestionsSchema) as ToolInput,
		annotations: {
			title: "Get Data Source Suggestions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetRelevantQuestions,
		description: "Get relevant data questions from ThoughtSpot database",
		inputSchema: zodToJsonSchema(GetRelevantQuestionsSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			GetRelevantQuestionsOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Get Relevant Questions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetAnswer,
		description: "Get the answer to a question from ThoughtSpot database",
		inputSchema: zodToJsonSchema(GetAnswerSchema) as ToolInput,
		annotations: {
			title: "Get Answer for a Question",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
];

export const toolDefinitionsV2 = [
	{
		name: ToolName.CheckConnectivity,
		description: "Ping tool to test connectivity and authentication",
		inputSchema: zodToJsonSchema(PingSchema) as ToolInput,
		annotations: {
			title: "Check Connectivity",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateAnalysisSession,
		description:
			"Start an analytical session with ThoughtSpot's analytics agent. This is the first step in a three-step workflow: create a session, send a message, then poll for updates. Once created, use the returned `analytical_session_id` to send analytical questions via `send_session_message` and retrieve answers via `get_session_updates`. Sessions are conversational, so you can ask follow-up questions in the same session without creating a new one.",
		inputSchema: zodToJsonSchema(CreateConversationSchema) as ToolInput,
		outputSchema: zodToJsonSchema(CreateConversationOutputSchema) as ToolOutput,
		annotations: {
			title: "Start Analysis",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.SendSessionMessage,
		description:
			"Send a message to a session with ThoughtSpot’s analytics agent. The agent may take some time to think and generate a response, so the response will not be returned immediately. Instead, use the `get_session_updates` tool to query for the latest updates on the session. After the agent finishes responding (when `get_session_updates` returns `is_done: true`), you can send another message to the same session to ask follow-up questions without creating a new session.",
		inputSchema: zodToJsonSchema(SendConversationMessageSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			SendConversationMessageOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Send Analysis Request",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetSessionUpdates,
		description:
			"Get the latest updates from a ThoughtSpot analytics session. Call this after `send_session_message` to retrieve the agent's response. If `is_done` is false, call this tool again to continue polling, as the agent is still generating a response. An empty `session_updates` list while `is_done` is false is normal; it means the agent is still thinking. When `is_done` is true, the agent has finished and the results in `session_updates` are complete, so you can present them to the user or send a follow-up message in the same session.",
		inputSchema: zodToJsonSchema(GetConversationUpdatesSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			GetConversationUpdatesOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Check Analysis Updates",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateDashboard,
		description: "Create a dashboard from a list of answers.",
		inputSchema: zodToJsonSchema(CreateDashboardSchema) as ToolInput,
		outputSchema: zodToJsonSchema(CreateDashboardOutputSchema) as ToolOutput,
		annotations: {
			title: "Create Dashboard",
			readOnlyHint: false,
			destructiveHint: false,
		},
	},
];
