import { ToolSchema } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

const ToolInputSchema = ToolSchema.shape.inputSchema;
type ToolInput = z.infer<typeof ToolInputSchema>;

export const ToolOutputSchema = ToolSchema.shape.outputSchema;
type ToolOutput = z.infer<typeof ToolOutputSchema>;

// Schemas
export const PingSchema = z.object({});

export const GetRelevantQuestionsSchema = z.object({
	query: z
		.string()
		.describe(
			"The query to get relevant data questions for, this could be a high level task or question the user is asking or hoping to get answered. Do minimal processing of the original question. You can even pass the complete raw query as it is, the system is smart to make sense of it as it has access to the entire schema. Do not add analytical hints or directions.",
		),
	additionalContext: z
		.string()
		.describe(
			"Additional context to add to the query, this might be older data returned for previous questions or any other relevant context that might help the system generate better questions.",
		)
		.optional(),
	datasourceIds: z
		.array(z.string())
		.describe(
			"The datasources to get questions for, this is the ids of the datasources to get data from. Each id is a GUID string.",
		),
});

export const GetRelevantQuestionsOutputSchema = z.object({
	questions: z.array(
		z.object({
			question: z.string(),
			datasourceId: z.string(),
		}),
	),
});

export const GetAnswerSchema = z.object({
	question: z
		.string()
		.describe(
			"The question to get the answer for, these are generally the questions generated by the getRelevantQuestions tool.",
		),
	datasourceId: z
		.string()
		.describe(
			"The datasource to get the answer for, this is the id of the datasource to get data from",
		),
});

export const GetAnswerOutputSchema = z.object({
	data: z.string().describe("The csv data as an answer to the question"),
	session_identifier: z
		.string()
		.describe(
			"The session identifier for the answer, use for liveboard creation",
		),
	generation_number: z
		.number()
		.describe(
			"The generation number for the answer, use for liveboard creation",
		),
	frame_url: z
		.string()
		.describe(
			"A url which can be used to view the answer in an iframe in the browser",
		),
	fields_info: z
		.string()
		.describe("Information about the fields in the answer"),
});

export const CreateConversationSchema = z.object({
	dataSourceId: z
		.string()
		.optional()
		.describe(
			"Sets the data source for the conversation. If not provided, the most relevant data source will be automatically selected based on the conversation.",
		),
});

export const CreateConversationOutputSchema = z.object({
	conversationId: z
		.string()
		.describe(
			"Identifier for the conversation. Use this to send messages or get updates on the conversation.",
		),
});

export const SendConversationMessageSchema = z.object({
	conversationId: z
		.string()
		.describe("Identifier of the conversation to send messages to."),
	messages: z
		.array(z.string())
		.describe("The messages to send to the conversation."),
});

export const SendConversationMessageOutputSchema = z.object({
	success: z.boolean().describe("Whether the messages were sent successfully."),
});

export const GetConversationUpdatesSchema = z.object({
	conversationId: z
		.string()
		.describe("Identifier of the conversation to get updates from."),
});

export const ConversationUpdateSchema = z.object({
	type: z.enum(["text", "answer"]).describe("The type of the update."),
	text: z
		.string()
		.optional()
		.describe("For a text message, the text content of the message."),
	answerTitle: z
		.string()
		.optional()
		.describe(
			"For an answer message, the title of the answer. This describes the overall content of the answer.",
		),
	answerQuery: z
		.string()
		.optional()
		.describe(
			"For an answer message, the full search query of the answer. This outlines the specific search being performed to generate the answer.",
		),
	answerFrameUrl: z
		.string()
		.optional()
		.describe(
			"For an answer message, the embeddable URL for the answer. If you are capable of displaying webpages in an iframe, you can use this URL to display an interactive answer visualization.",
		),
});

export const GetConversationUpdatesOutputSchema = z.object({
	conversationUpdates: z
		.array(ConversationUpdateSchema)
		.describe("The updates from the conversation."),
	isDone: z
		.boolean()
		.describe(
			"Whether the ThoughtSpot agent is finished responding to the conversation. If not done yet, make another GetConversationUpdates call to get the next set of updates.",
		),
});

export const CreateLiveboardSchema = z.object({
	name: z.string().describe("The name of the liveboard to create"),
	answers: z
		.array(
			z.object({
				question: z.string(),
				session_identifier: z.string(),
				generation_number: z.number(),
			}),
		)
		.describe(
			"The answers to create the liveboard from, these are the answers generated by the getAnswer tool.",
		),
	noteTile: z.string().describe(`
        Create a summary of the answers to the queries asked by the user along with all the analysis done on the data.
        The output format is an html note tile which can have custom styles and formatting. Use emojis, styling and icons to make it more visually appealing.
        Follow these MANDATORY rules for styling:
        - Put the whole note tile in a single line and no line breaks. Also there should be no unnecessary white spaces.
        - The html output in the note tile can have white spaces. Use <br> or <tab> if needed to use white spaces in the note tile.
        - Use padding, margin and line height to create space between the elements in the note tile and make it more readable.

        Use this as an example(ignore the line breaks and white spaces):

        <h2 class=\"theme-module__editor-h2\" dir=\"ltr\" style=\"text-align: center;\">
	        <span style=\"white-space: pre-wrap;\">\"Heading of note\"</span>
        </h2>
        <p class=\"theme-module__editor-paragraph\" dir=\"ltr\">
            <span style=\"white-space: pre-wrap;\">
                Comprehensive summary of analysis done and answers to queries asked by user. Use colors and styles in the html to make it more readable and visually appealing.
                Also add the date and time of the analysis to the note tile in the header of the note tile. The format should be like this: Generated on <date> <time>
            </span>
        </p>
        <div class=\"pinboard-note-tile-module__noteTileBg editor-module__bgNode\"></div>
        `),
});

export const GetDataSourceSuggestionsSchema = z.object({
	query: z
		.string()
		.describe(`The query to get data source suggestions for, this could be a high level task or question the user is asking or hoping to get answered.
         There can be multiple data sources. Each data source can be used to get the data for the user's query using the other tools getRelevantQuestions and getAnswer.`),
});

export enum ToolName {
	Ping = "ping",
	GetRelevantQuestions = "getRelevantQuestions",
	GetAnswer = "getAnswer",
	CreateConversation = "createConversation",
	SendConversationMessage = "sendConversationMessage",
	GetConversationUpdates = "getConversationUpdates",
	CreateLiveboard = "createLiveboard",
	GetDataSourceSuggestions = "getDataSourceSuggestions",
}

export const toolDefinitionsMCPServer = [
	{
		name: ToolName.Ping,
		description: "Simple ping tool to test connectivity and Auth",
		inputSchema: zodToJsonSchema(PingSchema) as ToolInput,
		annotations: {
			title: "Test Connection",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateLiveboard,
		description: "Create a liveboard from a list of answers",
		inputSchema: zodToJsonSchema(CreateLiveboardSchema) as ToolInput,
		annotations: {
			title: "Create Liveboard from Answers",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetDataSourceSuggestions,
		description:
			"Get data source suggestions for a query. Use this tool only if there is not datasource id provided in the context or the users query. If mulitple data sources are returned, and the confidence difference between the top two data sources is less than 0.3, ask the user to select the most relevant data source. Otherwise use the data source with the highest confidence to get the relevant questions and answers for the query.",
		inputSchema: zodToJsonSchema(GetDataSourceSuggestionsSchema) as ToolInput,
		annotations: {
			title: "Get Data Source Suggestions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetRelevantQuestions,
		description: "Get relevant data questions from ThoughtSpot database",
		inputSchema: zodToJsonSchema(GetRelevantQuestionsSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			GetRelevantQuestionsOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Get Relevant Questions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetAnswer,
		description: "Get the answer to a question from ThoughtSpot database",
		inputSchema: zodToJsonSchema(GetAnswerSchema) as ToolInput,
		annotations: {
			title: "Get Answer for a Question",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
];

export const toolDefinitionsMCPServerSpotter3 = [
	{
		name: ToolName.Ping,
		description: "Simple ping tool to test connectivity and Auth",
		inputSchema: zodToJsonSchema(PingSchema) as ToolInput,
		annotations: {
			title: "Test Connection",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateLiveboard,
		description: "Create a liveboard from a list of answers",
		inputSchema: zodToJsonSchema(CreateLiveboardSchema) as ToolInput,
		annotations: {
			title: "Create Liveboard from Answers",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.CreateConversation,
		description: "Begin a conversation with Spotter agent",
		inputSchema: zodToJsonSchema(CreateConversationSchema) as ToolInput,
		outputSchema: zodToJsonSchema(CreateConversationOutputSchema) as ToolOutput,
		annotations: {
			title: "Begin a conversation with Spotter agent",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.SendConversationMessage,
		description: "Send messages to a conversation with Spotter agent",
		inputSchema: zodToJsonSchema(SendConversationMessageSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			SendConversationMessageOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Send messages to a conversation with Spotter agent",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
	{
		name: ToolName.GetConversationUpdates,
		description: "Get response updates from a conversation with Spotter agent",
		inputSchema: zodToJsonSchema(GetConversationUpdatesSchema) as ToolInput,
		outputSchema: zodToJsonSchema(
			GetConversationUpdatesOutputSchema,
		) as ToolOutput,
		annotations: {
			title: "Get response updates from a conversation with Spotter agent",
			readOnlyHint: true,
			destructiveHint: false,
		},
	},
];
