import { z } from "zod";

export const PingSchema = z.object({});

export const GetRelevantQuestionsSchema = z.object({
	query: z
		.string()
		.describe(
			"The query to get relevant data questions for, this could be a high level task or question the user is asking or hoping to get answered. Do minimal processing of the original question. You can even pass the complete raw query as it is, the system is smart to make sense of it as it has access to the entire schema. Do not add analytical hints or directions.",
		),
	additionalContext: z
		.string()
		.describe(
			"Additional context to add to the query, this might be older data returned for previous questions or any other relevant context that might help the system generate better questions.",
		)
		.optional(),
	datasourceIds: z
		.array(z.string())
		.describe(
			"The datasources to get questions for, this is the ids of the datasources to get data from. This field is required. Each id is a GUID string of the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. An example datasource id is 123e4567-e89b-12d3-a456-426614174000. If a datasource name is provided instead of id, use the getDataSourceSuggestions tool to get the corresponding datasource id and use that to get relevant questions.",
		),
});

export const GetRelevantQuestionsOutputSchema = z.object({
	questions: z.array(
		z.object({
			question: z.string(),
			datasourceId: z.string(),
		}),
	),
});

export const GetAnswerSchema = z.object({
	question: z
		.string()
		.describe(
			"The question to get the answer for, these are generally the questions generated by the getRelevantQuestions tool.",
		),
	datasourceId: z
		.string()
		.describe(
			"The datasources to get questions for, this is the ids of the datasources to get data from. This field is required. Each id is a GUID string of the format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. An example datasource id is 123e4567-e89b-12d3-a456-426614174000. If a datasource name is provided instead of id, use the getDataSourceSuggestions tool to get the corresponding datasource id and use that to get relevant questions.",
		),
});

export const GetAnswerOutputSchema = z.object({
	data: z.string().describe("The csv data as an answer to the question"),
	session_identifier: z
		.string()
		.describe(
			"The session identifier for the answer, use for liveboard creation",
		),
	generation_number: z
		.number()
		.describe(
			"The generation number for the answer, use for liveboard creation",
		),
	frame_url: z
		.string()
		.describe(
			"A url which can be used to view the answer in an iframe in the browser",
		),
	fields_info: z
		.string()
		.describe("Information about the fields in the answer"),
});

export const CheckConnectivityInputSchema = z.object({});

export const CheckConnectivityOutputSchema = z.object({
	success: z
		.boolean()
		.describe(
			"Whether the request was successful. If unsuccessful, you can ask the user to verify their MCP server configuration.",
		),
});

export const CreateAnalysisSessionInputSchema = z.object({
	data_source_id: z
		.string()
		.optional()
		.describe(
			'The ID of the data source to query. You can provide this when the user has specified or confirmed a data source, or when context makes a particular source obvious. Omit it to let the Analytics Agent automatically select the most relevant source based on the question. A valid ID follows the following format: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (for example, "de1b3cfd-1725-400a-b6c7-0cd0f2b70bf1"). If you only have the data source name but not the ID, you can provide it in the `additional_context` field of the `send_session_message` tool instead.',
		),
});

export const CreateAnalysisSessionOutputSchema = z.object({
	analytical_session_id: z
		.string()
		.describe(
			"Identifier for the analytical session. You can use this to send messages or get updates on the session.",
		),
});

export const SendSessionMessageInputSchema = z.object({
	analytical_session_id: z
		.string()
		.describe("Identifier of the analytical session to send the message to."),
	message: z
		.string()
		.describe(
			"A natural language analytical question or follow-up to send to the Analytics Agent.",
		),
	additional_context: z
		.string()
		.optional()
		.describe(
			'Extra information which the Analytics Agent should be aware of while interpreting the `message`. You can use this field to provide background or external information relevant to the request, which the Agent would not be aware of. For example, "The user\'s fiscal year starts in April", or "The user is a manager of the West region".',
		),
});

export const SendSessionMessageOutputSchema = z.object({
	success: z
		.boolean()
		.describe(
			"Whether the message was successfully sent. If unsuccessful, you can try sending the message again, or creating a new analytical session.",
		),
});

export const GetSessionUpdatesInputSchema = z.object({
	analytical_session_id: z
		.string()
		.describe("Identifier of the analytical session to get updates from."),
});

export const ConversationUpdateSchema = z.object({
	type: z
		.enum(["text", "text_chunk", "answer"])
		.describe(
			"The type of update: `text` or `text_chunk` for a natural language message from the Analytics Agent, or `answer` for a data visualization with query results. Determines which other fields are populated.",
		),
	is_thinking: z
		.boolean()
		.describe(
			"Whether this update is part of the Analytics Agent's thinking process. You can use this to separate thinking updates from final result updates. You can use the thinking updates to show intermediate status or progress information to the user.",
		),
	text: z
		.string()
		.optional()
		.describe(
			"The text content of the message. Only present when `type` is `text` or `text_chunk`. If `type` is `text_chunk`, concatenate the chunks of text together in the order received to form the complete message.",
		),
	answer_id: z
		.string()
		.optional()
		.describe(
			"A unique identifier for the answer. Only present when `type` is `answer`. You can use this field to identify this answer when using the `create_dashboard` tool.",
		),
	answer_title: z
		.string()
		.optional()
		.describe(
			"A human-readable title describing what the answer shows. Only present when `type` is `answer`.",
		),
	answer_data_source_id: z
		.string()
		.optional()
		.describe(
			"The identifier of the data source which the answer is created on. Only present when `type` is `answer`. You can use this to understand which answers were created with the same data source, or to initiate future conversations using the same data source.",
		),
	answer_query: z
		.string()
		.optional()
		.describe(
			"The search query which the Analytics Agent used to generate the answer. Only present when `type` is `answer`. You can use this to explain to the user what data was queried, or to diagnose unexpected results.",
		),
	iframe_url: z
		.string()
		.optional()
		.describe(
			"An embeddable URL for displaying the answer as an interactive visualization. Only present when `type` is `answer`. You can use this to render a live chart or table if your environment supports iframes.",
		),
});

export const GetSessionUpdatesOutputSchema = z.object({
	session_updates: z
		.array(ConversationUpdateSchema)
		.describe(
			"List of incremental new updates from the analytical session. Updates returned in a previous response will not be sent again. This may be an empty list if the Analytics Agent is still thinking. You can instead use the `is_done` flag to know whether the Agent response is complete.",
		),
	is_done: z
		.boolean()
		.describe(
			"Whether the Analytics Agent has finished responding. If `is_done` is false, you can make another `get_session_updates` call to get the next set of updates.",
		),
});

export const CreateLiveboardSchema = z.object({
	name: z.string().describe("The name of the liveboard to create"),
	answers: z
		.array(
			z.object({
				question: z.string(),
				session_identifier: z.string(),
				generation_number: z.number(),
			}),
		)
		.describe(
			"The answers to create the liveboard from, these are the answers generated by the getAnswer tool.",
		),
	noteTile: z.string().describe(`
        Create a summary of the answers to the queries asked by the user along with all the analysis done on the data.
        The output format is an html note tile which can have custom styles and formatting. Use emojis, styling and icons to make it more visually appealing.
        Follow these MANDATORY rules for styling:
        - Put the whole note tile in a single line and no line breaks. Also there should be no unnecessary white spaces.
        - The html output in the note tile can have white spaces. Use <br> or <tab> if needed to use white spaces in the note tile.
        - Use padding, margin and line height to create space between the elements in the note tile and make it more readable.

        Use this as an example(ignore the line breaks and white spaces):

        <h2 class=\"theme-module__editor-h2\" dir=\"ltr\" style=\"text-align: center;\">
	        <span style=\"white-space: pre-wrap;\">\"Heading of note\"</span>
        </h2>
        <p class=\"theme-module__editor-paragraph\" dir=\"ltr\">
            <span style=\"white-space: pre-wrap;\">
                Comprehensive summary of analysis done and answers to queries asked by user. Use colors and styles in the html to make it more readable and visually appealing.
                Also add the date and time of the analysis to the note tile in the header of the note tile. The format should be like this: Generated on <date> <time>
            </span>
        </p>
        <div class=\"pinboard-note-tile-module__noteTileBg editor-module__bgNode\"></div>
        `),
});

export const GetDataSourceSuggestionsSchema = z.object({
	query: z
		.string()
		.describe(`The query to get data source suggestions for, this could be a high level task or question the user is asking or hoping to get answered.
         There can be multiple data sources. Each data source can be used to get the data for the user's query using the other tools getRelevantQuestions and getAnswer.`),
});

export const AnswerSchema = z.object({
	answer_id: z
		.string()
		.describe(
			"The unique identifier for the answer. Provide the `answer_id` value returned from get_session_updates for an update where `type` is `answer`.",
		),
	title: z
		.string()
		.describe(
			"Title of the answer. Provide a brief description of the answer, or the question which the answer is answering.",
		),
});

/**
 * Guidance reused across the dashboard tools. Kept in one place so `create_dashboard` and
 * `modify_dashboard` describe the same capability the same way.
 */
const DESIGN_CONTEXT_GUIDANCE = `Free-form description of how the dashboard should look and be organised. There is no length limit, so pass as much detail as you have: if you are migrating a dashboard from another tool (for example a Tableau workbook), describe its charts, groupings, tabs, ordering and colours here in your own words.

What is worth including, because the dashboard designer acts on it:
- The data source to use, by name or id. This is the single most important item. Without it the tool will come back asking which data source to use instead of building anything.
- Grouping and tabs: which charts belong together, and whether they should be split across tabs.
- Narrative order: what matters most. Key figures and headline metrics are placed top-left first.
- Chart types per metric, stated literally (for example "revenue by region as a column chart"). Use the user's exact wording for measures and dimensions; it is interpreted literally.
- Brand colours as hex codes.
- Any short explanatory text you want on the dashboard. Keep it brief and do not put live figures such as amounts, counts or percentages in it.

What it cannot do, so do not ask for it: changing the chart type of an existing chart (it has to be recreated instead), editing an existing chart's columns or query, and colouring individual data values (for example red for "Churn").`;

/** One line for tools that are not entry points, so the full contract is not sent three times. */
const RESULT_CONTRACT_BRIEF =
	"Check `status`: `completed` (give the user `dashboard_url`), `in_progress` (call this again), `needs_input` (`question` says what is needed; answer it via `modify_dashboard` with the same `dashboard_id` and `task_id`), `failed` (see `error`).";

const RESULT_CONTRACT_GUIDANCE = `Check \`status\` on the result and act on it:
- \`completed\`: the dashboard is saved. Give the user \`dashboard_url\`.
- \`needs_input\`: the designer needs more detail before it can proceed, and nothing has changed yet. \`question\` holds exactly what it asked, and \`choices\` any options it offered. **It is your decision how to resolve this.** If you can answer it yourself, for example you already know which data source to use or can resolve it from what the user told you earlier, just answer it. Only ask the user when you genuinely cannot. Either way, continue by calling \`modify_dashboard\` with the same \`dashboard_id\` and \`task_id\`, putting the answer in \`instructions\`. Do not abandon the request and do not report it to the user as finished.
- \`in_progress\`: still working. Call \`get_dashboard_status\` with \`task_id\` to continue, and keep calling it until you get another status.
- \`failed\`: nothing usable was produced. \`error\` explains why.`;

/**
 * Shared result shape for the dashboard tools.
 *
 * Field prose is deliberately sparse. This schema ships on all three tools, so every sentence here
 * is sent three times on every request. Anything the status contract in the tool description
 * already explains (how to use `task_id`, what to do per status) is not repeated here, and fields
 * whose names say what they are carry no description at all.
 */
export const DashboardResultSchema = z.object({
	status: z
		.enum(["completed", "in_progress", "needs_input", "failed"])
		.describe(
			"Outcome of the request. See the tool description for what to do for each value.",
		),
	dashboard_id: z.string().optional(),
	dashboard_url: z.string().optional(),
	task_id: z.string().optional(),
	changes_applied: z
		.boolean()
		.optional()
		.describe(
			"Whether the dashboard actually changed. False with `completed` means the request was understood but changed nothing.",
		),
	summary: z.string().optional().describe("What the designer reported."),
	steps: z.array(z.string()).optional(),
	events_seen: z
		.number()
		.optional()
		.describe(
			"Progress so far while `in_progress`. Rising between calls means it is working; stuck at 0 may mean it is not.",
		),
	question: z
		.string()
		.optional()
		.describe(
			"What the designer needs from you when `status` is `needs_input`.",
		),
	choices: z
		.array(z.string())
		.optional()
		.describe("Options the designer offered alongside `question`."),
	error: z.string().optional().describe("Why it failed."),
});

export const CreateDashboardInputSchema = z
	.object({
		title: z.string().describe("Title of the dashboard to be created."),
		design_context: z.string().optional().describe(DESIGN_CONTEXT_GUIDANCE),
		data_source_id: z
			.string()
			.optional()
			.describe(
				'Id of the data source to build new charts from, in the format "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx". Required when you do not pass `answers`, because the charts have to be created from somewhere. If you only know the data source name, use `get_data_source_suggestions` to resolve it, or name it inside `design_context`.',
			),
		answers: z
			.array(AnswerSchema)
			.optional()
			.describe(
				"List of answers to add to the dashboard, from a prior analysis. Omit this when you have no answers yet and want the charts built from `design_context` instead, in which case you must pass `data_source_id`.",
			),
		skip_layout: z
			.boolean()
			.optional()
			.describe(
				"Set true to skip organising and styling, returning as soon as the answers are assembled. The result is a plain uniform grid in the order of `answers`, so only use this when the user explicitly wants the raw dashboard quickly and does not care how it looks.",
			),
	})
	.refine((d) => (d.answers && d.answers.length > 0) || d.design_context, {
		message:
			"Provide `answers` from a prior analysis, or `design_context` describing the dashboard to build, or both.",
	})
	.refine((d) => (d.answers && d.answers.length > 0) || d.data_source_id, {
		message:
			"`data_source_id` is required when `answers` is not provided, because the charts have to be created from a data source.",
	});

export const CreateDashboardOutputSchema = DashboardResultSchema.extend({
	link: z
		.string()
		.optional()
		.describe(
			"A URL link to the created dashboard. Retained for backwards compatibility; prefer `dashboard_url`.",
		),
});

export const ModifyDashboardInputSchema = z.object({
	dashboard_id: z
		.string()
		.min(1)
		.describe(
			'Id of the dashboard to change, in the format "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx". Always required, including when continuing earlier work with `task_id`, so that every call states which dashboard it is changing. If you do not have the id, ask the user for it or for the dashboard link, which ends in `/pinboard/<id>`. Do not guess it and do not pass a dashboard name here.',
		),
	task_id: z
		.string()
		.optional()
		.describe(
			"Handle returned by a previous `create_dashboard` or `modify_dashboard` call. Pass it alongside `dashboard_id` to answer a question the designer asked, or to send a follow-up instruction, which keeps the earlier context. Omit it to start a fresh change. It must belong to the same `dashboard_id`.",
		),
	instructions: z
		.string()
		.min(1)
		.describe(
			"What to change, in plain language. This can be a layout or styling change, a request to add new charts, or an answer to a question the designer asked you. Include the same kind of detail described for `design_context` on `create_dashboard`, and name the data source when the change needs new charts.",
		),
	data_source_id: z
		.string()
		.optional()
		.describe(
			"Id of the data source to use if the change requires new charts. Without it, a request that needs new charts will come back asking which data source to use.",
		),
});

export const ModifyDashboardOutputSchema = DashboardResultSchema;

export const GetDashboardStatusInputSchema = z.object({
	task_id: z
		.string()
		.describe(
			"The `task_id` returned by `create_dashboard` or `modify_dashboard` when `status` was `in_progress`.",
		),
});

export const GetDashboardStatusOutputSchema = DashboardResultSchema;

export const SpotterVizCreateSessionInputSchema = z
	.object({
		new_liveboard_name: z
			.string()
			.optional()
			.describe(
				"Name for a new, empty liveboard to be created. Provide this when the user wants to start a SpotterViz session from scratch.",
			),
		existing_liveboard_id: z
			.uuid()
			.optional()
			.describe(
				"GUID of an existing liveboard to open in SpotterViz (the format is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). Provide this when the user wants to continue with an existing liveboard instead of creating a new one.",
			),
	})
	.refine(
		(d) =>
			(d.new_liveboard_name === undefined) !==
			(d.existing_liveboard_id === undefined),
		{
			message:
				"Exactly one of `new_liveboard_name` or `existing_liveboard_id` must be provided.",
		},
	);

export const SpotterVizCreateSessionOutputSchema = z.object({
	spotterviz_session_id: z
		.string()
		.describe(
			"Identifier for the SpotterViz session. Use this with future spotterviz_send_message / spotterviz_get_updates calls.",
		),
	liveboard_id: z
		.string()
		.describe("GUID of the liveboard the session is bound to."),
	liveboard_name: z
		.string()
		.optional()
		.describe("Display name of the liveboard, if known."),
});

export const SpotterVizSubmitQueryInputSchema = z.object({
	spotterviz_session_id: z
		.string()
		.describe(
			"Identifier of the SpotterViz session to send the message to. Use the value returned from `spotterviz_create_session`.",
		),
	message: z
		.string()
		.min(1)
		.max(2000)
		.describe(
			"Natural-language instruction or question to send to the SpotterViz agent. Maximum 2000 characters.",
		),
});

export const SpotterVizSubmitQueryOutputSchema = z.object({
	success: z
		.boolean()
		.describe(
			"Whether the message was accepted and streaming started. After this returns, poll `spotterviz_get_updates` for the agent's response.",
		),
});

export const SpotterVizGetUpdatesInputSchema = z.object({
	spotterviz_session_id: z
		.string()
		.describe(
			"Identifier of the SpotterViz session to fetch updates from. Use the value returned from `spotterviz_create_session`.",
		),
});

export const SpotterVizUpdateSchema = z.object({
	event_type: z
		.string()
		.describe(
			"The Aurora SSE event type (e.g. `message.delta`, `control.action`, `meta.error`).",
		),
	data: z
		.record(z.string(), z.unknown())
		.describe("Raw event payload as emitted by Aurora."),
	message_id: z.string().nullish(),
	idx: z.number().nullish(),
	timestamp: z.string().nullish(),
	tool_id: z.string().nullish(),
	group_id: z.string().nullish(),
	heading: z.string().nullish(),
});

export const SpotterVizGetUpdatesOutputSchema = z.object({
	updates: z
		.array(SpotterVizUpdateSchema)
		.describe(
			"Incremental SSE events emitted by the SpotterViz agent since the last call. Empty when the agent is still thinking and no new events have arrived within the wait window.",
		),
	is_done: z
		.boolean()
		.describe(
			"Whether the SpotterViz agent has finished responding for this turn. If false, call this tool again to continue polling.",
		),
});

export const SpotterVizSaveLiveboardInputSchema = z.object({
	spotterviz_session_id: z
		.string()
		.describe(
			"Identifier of the SpotterViz session whose current liveboard state should be saved. Use the value returned from `spotterviz_create_session`.",
		),
});

export const SpotterVizSaveLiveboardOutputSchema = z.object({
	liveboard_id: z.string().describe("GUID of the saved liveboard."),
	liveboard_url: z
		.string()
		.describe(
			"URL where the user can view the saved liveboard in ThoughtSpot. Provide this link to the user when reporting that the liveboard was saved.",
		),
});

export const ListOrgsInputSchema = z.object({});

export const ListOrgsOutputSchema = z.object({
	orgs: z
		.array(
			z.object({
				id: z.number().describe("Unique identifier of the Org."),
				name: z.string().describe("Name of the Org."),
				description: z.string().optional().describe("Description of the Org."),
				is_active: z
					.boolean()
					.optional()
					.describe(
						"Present and true only for the Org currently active for your account. Absent for all other Orgs. Tool calls operate against the active Org.",
					),
			}),
		)
		.describe("The list of Orgs the user can access."),
});

export const SwitchOrgInputSchema = z.object({
	org_id: z
		.number()
		.describe(
			"The id of the Org to switch to. Use an `id` returned by `list_orgs`. Subsequent tool calls in this session operate against this Org.",
		),
});

export const SwitchOrgOutputSchema = z.object({
	success: z.boolean().describe("Whether the Org switch was successful."),
	active_org_id: z
		.number()
		.describe("The id of the Org now active for the session."),
});

export enum ToolName {
	// V1
	Ping = "ping",
	GetRelevantQuestions = "getRelevantQuestions",
	GetAnswer = "getAnswer",
	CreateLiveboard = "createLiveboard",
	GetDataSourceSuggestions = "getDataSourceSuggestions",
	// V2 (Spotter 3)
	CheckConnectivity = "check_connectivity",
	CreateAnalysisSession = "create_analysis_session",
	SendSessionMessage = "send_session_message",
	GetSessionUpdates = "get_session_updates",
	CreateDashboard = "create_dashboard",
	ModifyDashboard = "modify_dashboard",
	GetDashboardStatus = "get_dashboard_status",
	ListOrgs = "list_orgs",
	SwitchOrg = "switch_org",
	// SpotterViz (Aurora)
	SpotterVizCreateSession = "spotterviz_create_session",
	SpotterVizSubmitQuery = "spotterviz_submit_query",
	SpotterVizGetUpdates = "spotterviz_get_updates",
	SpotterVizSaveLiveboard = "spotterviz_save_liveboard",
}

export const toolDefinitionsV1 = [
	{
		name: ToolName.Ping,
		description: "Simple ping tool to test connectivity and Auth",
		inputSchema: z.toJSONSchema(PingSchema),
		annotations: {
			title: "Test Connection",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.CreateLiveboard,
		description: "Create a liveboard from a list of answers",
		inputSchema: z.toJSONSchema(CreateLiveboardSchema),
		annotations: {
			title: "Create Liveboard from Answers",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.GetDataSourceSuggestions,
		description:
			"Get data source suggestions for a query. Use this tool only if there is not datasource id provided in the context or the users query. If mulitple data sources are returned, and the confidence difference between the top two data sources is less than 0.3, ask the user to select the most relevant data source. Otherwise use the data source with the highest confidence to get the relevant questions and answers for the query.",
		inputSchema: z.toJSONSchema(GetDataSourceSuggestionsSchema),
		annotations: {
			title: "Get Data Source Suggestions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.GetRelevantQuestions,
		description: "Get relevant data questions from ThoughtSpot database",
		inputSchema: z.toJSONSchema(GetRelevantQuestionsSchema),
		outputSchema: z.toJSONSchema(GetRelevantQuestionsOutputSchema),
		annotations: {
			title: "Get Relevant Questions for a Query",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.GetAnswer,
		description: "Get the answer to a question from ThoughtSpot database",
		inputSchema: z.toJSONSchema(GetAnswerSchema),
		annotations: {
			title: "Get Answer for a Question",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
];

export const toolDefinitionsV2 = [
	{
		name: ToolName.CheckConnectivity,
		description:
			"Ping tool to test connectivity and authentication. You can use this if other tool calls are failing to verify if the connection is working.",
		inputSchema: z.toJSONSchema(CheckConnectivityInputSchema),
		outputSchema: z.toJSONSchema(CheckConnectivityOutputSchema),
		annotations: {
			title: "Check Connectivity",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.CreateAnalysisSession,
		description:
			"Start an analytical session with the Analytics Agent. This is the first step in a three-step workflow: create a session, send a message, then poll for updates. Once created, you can use the returned `analytical_session_id` to send analytical questions via `send_session_message` and retrieve answers via `get_session_updates`. Sessions are conversational, so you can ask follow-up questions in the same session without creating a new one. Using a single analytical session is preferable, because it reuses the same data source selection. When the user's intent is to create a dashboard, use the first message in this session to plan: ask the Analytics Agent what data and metrics are available for the topic, what trends or breakdowns would be most meaningful, and what chart types best fit the data. Use the Agent's response to form a dashboard plan before requesting any specific charts.",
		inputSchema: z.toJSONSchema(CreateAnalysisSessionInputSchema),
		outputSchema: z.toJSONSchema(CreateAnalysisSessionOutputSchema),
		annotations: {
			title: "Create Analysis Session",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SendSessionMessage,
		description:
			"Send a message to a session with the Analytics Agent. The Agent may take some time to think and generate a response, so the response will not be returned immediately. Instead, you can use the `get_session_updates` tool to query for the latest updates on the session. After the Agent finishes responding (when `get_session_updates` returns `is_done: true`), you can send another message to the same session to ask follow-up questions without creating a new session. Do not send a new message until the Agent has finished responding to the previous message (when `get_session_updates` returns `is_done: true`). When the user's intent is to create a dashboard, the first message must be a planning query — ask what data and metrics are available, what key breakdowns or trends exist, and what charts would be most insightful. Only after receiving and synthesising the Agent's planning response should you send follow-up messages to request specific charts. If the user wants to create a dashboard from the charts collected, use the `create_dashboard` tool — do not send that request as a message to the Agent.",
		inputSchema: z.toJSONSchema(SendSessionMessageInputSchema),
		outputSchema: z.toJSONSchema(SendSessionMessageOutputSchema),
		annotations: {
			title: "Send Analysis Session Message",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.GetSessionUpdates,
		description:
			"Get the latest updates from the Analytics Agent. You can call this after `send_session_message` to retrieve the Agent's response. If `is_done` is false, you can call this tool again to continue polling, as the Agent is still generating a response. Even if `is_done` is false, you can use the updates to show status updates or progress to the user, so that they are informed about the ongoing process. An empty `session_updates` list while `is_done` is false is normal; it means the Agent is still thinking. When `is_done` is true, the Agent has finished and the results in `session_updates` are complete, so you can present them to the user. You can also send a follow-up message in the same session after `is_done` is true. If the completed response indicates that no data or no results were found, AND the `list_orgs` tool is available to you, the requested data may live in a different org or the user may not have access to it in the current org: tell the user this and that they can call `list_orgs` to see their orgs (the active one is marked `is_active`) and `switch_org` to switch to another org, then retry. If `list_orgs` is not available, do not mention orgs.",
		inputSchema: z.toJSONSchema(GetSessionUpdatesInputSchema),
		outputSchema: z.toJSONSchema(GetSessionUpdatesOutputSchema),
		annotations: {
			title: "Get Analysis Session Updates",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.CreateDashboard,
		description: `Create a dashboard, organise it, and save it, so the user can revisit the results later or share them with others. Use this whenever the user asks for a dashboard or a liveboard, asks to save the results of an analysis, or asks to recreate a dashboard they have elsewhere.

There are two ways to call it, and you can combine them:
1. From analysis you already did: pass \`answers\` from \`get_session_updates\`. The charts you already have are assembled into a dashboard.
2. From a description: pass \`design_context\` describing the dashboard you want, plus \`data_source_id\`. The charts are created for you. Use this when the user has a template, a spec, or a dashboard from another tool (for example a Tableau workbook) that they want recreated.

**The dashboard is always organised and styled before it is saved**, so what you get back is presentable rather than a plain grid. Add \`design_context\` when the user has preferences about how it should look; leave it out and sensible choices are made for you. Because this includes a design pass, it can take a few minutes and may return before it is finished.

${RESULT_CONTRACT_GUIDANCE}`,
		inputSchema: z.toJSONSchema(CreateDashboardInputSchema),
		outputSchema: z.toJSONSchema(CreateDashboardOutputSchema),
		annotations: {
			title: "Create Dashboard",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.ModifyDashboard,
		description: `Change an existing dashboard. It can rearrange and restyle what is already there, add new charts, add short explanatory text, and organise charts into groups or tabs.

\`dashboard_id\` is always required, so that every call says which dashboard it is changing. Add \`task_id\` as well to continue something you already started, which is how you answer a question the designer asked you or send a follow-up instruction about the same dashboard.

Describe the change in \`instructions\` in plain language, and be specific: vague requests come back as questions rather than changes. If the change needs new charts, name the data source or pass \`data_source_id\`.

Changes are saved to the user's real dashboard automatically as they are made, so only call this when the user has asked for the dashboard to change. Changing a dashboard can take a few minutes, so this may return before it is finished.

${RESULT_CONTRACT_GUIDANCE}`,
		inputSchema: z.toJSONSchema(ModifyDashboardInputSchema),
		outputSchema: z.toJSONSchema(ModifyDashboardOutputSchema),
		annotations: {
			title: "Modify Dashboard",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.GetDashboardStatus,
		description: `Continue waiting for a dashboard that is still being built or changed. Call this when \`create_dashboard\` or \`modify_dashboard\` returned \`status: "in_progress"\`, passing the \`task_id\` they gave you.

Each call waits a short while before returning, so calling it repeatedly is the correct way to wait. Keep calling until \`status\` is \`completed\`, \`needs_input\` or \`failed\`. Do not abandon a task after one \`in_progress\` result, and do not start a new \`create_dashboard\` or \`modify_dashboard\` call for the same work, or you will create duplicate dashboards.

${RESULT_CONTRACT_BRIEF}`,
		inputSchema: z.toJSONSchema(GetDashboardStatusInputSchema),
		outputSchema: z.toJSONSchema(GetDashboardStatusOutputSchema),
		annotations: {
			title: "Get Dashboard Status",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SpotterVizCreateSession,
		description:
			"DEPRECATED and no longer listed: use `create_dashboard` and `modify_dashboard` instead, which do this in a single call. Low-level session primitive kept only for existing callers. Opens a SpotterViz session against a new or existing liveboard; exactly one of `new_liveboard_name` or `existing_liveboard_id` must be provided. The returned `spotterviz_session_id` is the identifier for the other `spotterviz_*` tools.",
		inputSchema: z.toJSONSchema(SpotterVizCreateSessionInputSchema),
		outputSchema: z.toJSONSchema(SpotterVizCreateSessionOutputSchema),
		annotations: {
			title: "Create SpotterViz Session",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SpotterVizSubmitQuery,
		description:
			"DEPRECATED and no longer listed: use `create_dashboard` and `modify_dashboard` instead, which do this in a single call. Low-level session primitive kept only for existing callers. Submits a prompt to an existing SpotterViz session; it can restyle and rearrange a liveboard and can also create new answers on it. The response streams asynchronously, so this returns as soon as streaming starts; poll `spotterviz_get_updates` for the response. Do not call it again on the same `spotterviz_session_id` until the previous turn is done, or it will be rejected.",
		inputSchema: z.toJSONSchema(SpotterVizSubmitQueryInputSchema),
		outputSchema: z.toJSONSchema(SpotterVizSubmitQueryOutputSchema),
		annotations: {
			title: "Submit SpotterViz Query",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SpotterVizGetUpdates,
		description:
			"Get the latest streaming events from a SpotterViz session. Call this after `spotterviz_submit_query` and continue polling until `is_done` is true. When `is_done` is true, immediately call `spotterviz_save_liveboard` — do not skip this step. The tool waits adaptively for new events (with internal exponential backoff up to 16 s) and returns early as soon as any events arrive or the turn finishes, so back-to-back calls cost no more than a quick poll when activity is high. An empty `updates` list with `is_done: false` simply means the agent is still thinking — call again to keep polling.",
		inputSchema: z.toJSONSchema(SpotterVizGetUpdatesInputSchema),
		outputSchema: z.toJSONSchema(SpotterVizGetUpdatesOutputSchema),
		annotations: {
			title: "Get SpotterViz Session Updates",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.ListOrgs,
		description:
			"List the Orgs the authenticated user can access on the ThoughtSpot instance, including the ID, name, and description of each Org. The Org marked `is_active: true` is the one currently active for your account, which all tool calls operate against. Use this to tell the user which Org they are in. Only available when authenticated via OAuth. If the list is large , summarize or show only the most relevant orgs (e.g. the active one and a few others) rather than listing all of them, unless the user explicitly asks to see all orgs.",
		inputSchema: z.toJSONSchema(ListOrgsInputSchema),
		outputSchema: z.toJSONSchema(ListOrgsOutputSchema),
		annotations: {
			title: "List Orgs",
			readOnlyHint: true,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SpotterVizSaveLiveboard,
		description:
			"Persist the current state of the SpotterViz session's liveboard back to ThoughtSpot. Always call this after `spotterviz_get_updates` returns `is_done: true` — do not end the SpotterViz flow without saving. The session stays active after saving, so further `spotterviz_submit_query` calls on the same session id continue to work. Returns a `liveboard_url` you must surface to the user as a direct link to the saved liveboard.",
		inputSchema: z.toJSONSchema(SpotterVizSaveLiveboardInputSchema),
		outputSchema: z.toJSONSchema(SpotterVizSaveLiveboardOutputSchema),
		annotations: {
			title: "Save SpotterViz Liveboard",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
	{
		name: ToolName.SwitchOrg,
		description:
			"Switch the active Org. After switching, all subsequent tool calls (analysis sessions, answers, data sources, dashboards) operate against the selected Org. Pass an `org_id` returned by `list_orgs`. If you do not have access to the Org, the switch fails and the active Org is unchanged. The selection is durable and shared across all of your sessions — it persists across reconnects and applies to your other active conversations; it resets only on re-authentication or after prolonged inactivity. Only available when authenticated via OAuth.",
		inputSchema: z.toJSONSchema(SwitchOrgInputSchema),
		outputSchema: z.toJSONSchema(SwitchOrgOutputSchema),
		annotations: {
			title: "Switch Org",
			readOnlyHint: false,
			destructiveHint: false,
			openWorldHint: false,
		},
	},
];
