openapi: 3.0.0
info:
  title: ThoughtSpot API
  version: 1.0.0
  description: API for interacting with ThoughtSpot services

servers:
  - url: https://thoughtspot-mcp-server-open-api.thoughtspot-485.workers.dev
    description: ThoughtSpot agent url

paths:
  /api/tools/create-liveboard:
    post:
      summary: Create a new liveboard
      description: Creates a new liveboard with the specified name and answers
      operationId: createLiveboard
      tags:
        - Tools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLiveboardRequest'
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                description: URL of the created liveboard
                example: "https://thoughtspot.thoughtspot.com/viz/123456"
        '400':
          description: Bad request - Invalid input parameters
        '401':
          description: Unauthorized - Invalid or missing authentication
        '500':
          description: Internal server error

components:
  schemas:
    CreateLiveboardRequest:
      type: object
      required:
        - name
        - answers
      properties:
        name:
          type: string
          description: Name of the liveboard to create
          example: "Sales Analysis Dashboard"
        answers:
          type: array
          description: List of answers to include in the liveboard
          items:
            type: object
            properties:
              question:
                type: string
                description: The question for this answer asked by the user
                example: "What are the monthly sales trends?"
              answer:
                type: string
                description: The answer to the question received in response to the get answer action
                example: "Monthly sales show an upward trend with peak in December"
              datasourceId:
                type: string
                description: The datasource ID used for this answer
                example: "123e4567-e89b-12d3-a456-426614174000"